### ISSUE TITLE
Await outside async function

### ISSUE THREAD

**Issue by RogaStr1ke** [nthmost/discord-radio-bot#1]
I've got this error after running python radiobot.py :
`    await ctx.send(f"You need to join a Voice Channel for me to know where to play the stream!")
    ^
SyntaxError: 'await' outside async function`

I'm noobie with Python, so i don't know hot to solve it

**Comment by nthmost** [comment]
Hey @RogaStr1ke , Sorry i didn't see this until now.

This is the exception that's supposed to happen when the user that your discord app is running with isn't currently sitting in a Voice channel.

To solve, just make sure that before you run this script, you have your bot user already sitting in a Voice channel ready to play the stream.

Since this isn't a bug i'm going to close this issue.  But if you need more help feel free to open a new one!
